# Create individual targets for each program
COMPILE_ALL = serial mutex rw_lock
all: $(COMPILE_ALL)

serial: serial.c linked_list.c
	gcc -o serial serial.c linked_list.c -lm

mutex: mutex.c linked_list.c
	gcc -o mutex mutex.c linked_list.c -lm

rw_lock: rw_lock.c linked_list.c
	gcc -o rw_lock rw_lock.c linked_list.c -lm

# Clean up compiled files
clean:
	rm -f $(ALL_TARGETS)

# Run the programs with the pre-defined arguments
RUN_ALL = run_serial run_mutex run_rw_lock
run_all: $(RUN_ALL)

run_serial: serial
	./serial .99 .005 .005

run_mutex: mutex
	./mutex 1 .99 .005 .005
	./mutex 2 .99 .005 .005
	./mutex 4 .99 .005 .005
	./mutex 8 .99 .005 .005
	./mutex 1 .9 .05 .05
	./mutex 2 .9 .05 .05
	./mutex 4 .9 .05 .05
	./mutex 8 .9 .05 .05
	./mutex 1 .5 .25 .25
	./mutex 2 .5 .25 .25
	./mutex 4 .5 .25 .25
	./mutex 8 .5 .25 .25

run_rw_lock: rw_lock
	./rw_lock 1 .99 .005 .005
	./rw_lock 2 .99 .005 .005
	./rw_lock 4 .99 .005 .005
	./rw_lock 8 .99 .005 .005
	./rw_lock 1 .9 .05 .05
	./rw_lock 2 .9 .05 .05
	./rw_lock 4 .9 .05 .05
	./rw_lock 8 .9 .05 .05
	./rw_lock 1 .5 .25 .25
	./rw_lock 2 .5 .25 .25
	./rw_lock 4 .5 .25 .25
	./rw_lock 8 .5 .25 .25

	
